#!/bin/bash
TRAGET=$HOME/shopify-review-wall
GIT_DIR=$HOME/shopify-review-wall.git
BRANCH="master"

while read oldrev newrev ref
do
	# only checking out the master (or whatever branch you would like to deploy)
	if [[ $ref = refs/heads/$BRANCH ]];
	then
		echo "Ref $ref received. Deploying ${BRANCH} branch to production..."
		git --work-tree=$TRAGET --git-dir=$GIT_DIR checkout -f

    cd $TRAGET
    docker-compose stop
    docker-compose up --build -d

    echo "Docker's built! Hurray!!!"
	else
		echo "Ref $ref received. Doing nothing: only the ${BRANCH} branch may be deployed on this server."
	fi
done
